In [4]:
import torch 

In [2]:
#reproducibility is important in neural networks and in general you start with a bunch of random tensors. 
#How do we control that randomness. 

#we introduce something called as the *random seed* which flavours the randomness


In [5]:
rand_tensora = torch.rand(3,4)
rand_tensorb = torch.rand(3,4)

In [6]:
rand_tensora, rand_tensorb

(tensor([[0.4428, 0.6821, 0.3664, 0.4990],
         [0.2701, 0.2212, 0.7033, 0.1821],
         [0.3628, 0.3052, 0.7857, 0.3721]]),
 tensor([[0.0216, 0.3284, 0.7494, 0.4905],
         [0.1022, 0.1825, 0.8805, 0.1772],
         [0.9769, 0.5014, 0.9426, 0.6399]]))

In [8]:
#setting the seed 

RANDOM_SEED = 12
torch.manual_seed(RANDOM_SEED)

random_tesnorc = torch.rand(3,4) 
random_tesnord = torch.rand(3,4)
random_tesnorc, random_tesnord #both this WONT work as manual seed applies to one block, where all tensors in that block are random. 
#if we reset the manual seed before creating tensor d then we can make sure they are the same. 

(tensor([[0.4657, 0.2328, 0.4527, 0.5871],
         [0.4086, 0.1272, 0.6373, 0.2421],
         [0.7312, 0.7224, 0.1992, 0.6948]]),
 tensor([[0.5830, 0.6318, 0.5559, 0.1262],
         [0.9790, 0.8443, 0.1256, 0.4456],
         [0.6601, 0.0554, 0.1573, 0.8137]]))

In [11]:
torch.manual_seed(RANDOM_SEED)
random_tensor_1 = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_2 = torch.rand(3,4)

random_tensor_1 == random_tensor_2 #they are truly equal, each element is. 

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])