In [1]:
import torch 

In [2]:
#reproducibility is important in neural networks and in general you start with a bunch of random tensors. 
#How do we control that randomness. 

#we introduce something called as the *random seed* which flavours the randomness


In [2]:
rand_tensora = torch.rand(3,4)
rand_tensorb = torch.rand(3,4)

In [3]:
rand_tensora, rand_tensorb

(tensor([[0.9803, 0.8403, 0.0658, 0.4089],
         [0.5734, 0.4422, 0.9817, 0.7240],
         [0.5583, 0.7801, 0.2178, 0.4446]]),
 tensor([[0.7662, 0.6934, 0.4806, 0.8272],
         [0.1346, 0.3669, 0.5893, 0.6600],
         [0.7615, 0.3138, 0.5332, 0.7374]]))

In [5]:
#setting the seed 

RANDOM_SEED = 12
torch.manual_seed(RANDOM_SEED)

random_tesnorc = torch.rand(3,4) 
random_tesnord = torch.rand(3,4)
random_tesnorc, random_tesnord #both of these WONT work as manual seed applies to one block, where all tensors in that block are random. 
#if we reset the manual seed before creating tensor d then we can make sure they are the same. 

(tensor([[0.4657, 0.2328, 0.4527, 0.5871],
         [0.4086, 0.1272, 0.6373, 0.2421],
         [0.7312, 0.7224, 0.1992, 0.6948]]),
 tensor([[0.5830, 0.6318, 0.5559, 0.1262],
         [0.9790, 0.8443, 0.1256, 0.4456],
         [0.6601, 0.0554, 0.1573, 0.8137]]))

In [6]:
torch.manual_seed(RANDOM_SEED)
random_tensor_1 = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_2 = torch.rand(3,4)

random_tensor_1 == random_tensor_2 #they are truly equal, each element is. 

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])