In [3]:
import torch 


Manipulating Tensors (Tensor Operations)

In [4]:
tensor1 = torch.tensor([1,2,3])
tensor1 + 10 #addition 

tensor([11, 12, 13])

In [5]:
tensor1 * 10 #multiply 

tensor([10, 20, 30])

In [8]:
tensor2 = torch.rand(3,4)
print(tensor2)

tensor([[0.2923, 0.8486, 0.2530, 0.1835],
        [0.8883, 0.6189, 0.9600, 0.0314],
        [0.4386, 0.5528, 0.3469, 0.3977]])


ELEMENT WISE MULTIPLICATION && MATRIX WISE MULITPLICATION

In [11]:
torch.mul(tensor2,10) #This is ELEMENT WISE MATRIX MULTIPLICATION : we multiply by a scalar value 

tensor([[2.9227, 8.4856, 2.5300, 1.8348],
        [8.8831, 6.1887, 9.6000, 0.3145],
        [4.3858, 5.5284, 3.4692, 3.9773]])

In [13]:
tensor3 = torch.rand(4,3)
print(tensor3)

tensor([[0.4699, 0.4226, 0.9939],
        [0.7588, 0.3698, 0.1217],
        [0.2761, 0.9962, 0.7635],
        [0.0332, 0.3749, 0.4038]])


In [15]:
tensor2 * tensor3 #this is an error even though this is 3 by 4 * 4 by 3. because its ELEMENT MULT 

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [17]:
torch.matmul(tensor2,tensor3) #THIS IS MATRIX MULTIPLICATION WHICH HAPPENS IN NEURAL NETWORKS 

tensor([[0.8571, 0.7582, 0.6610],
        [1.1531, 1.5724, 1.7039],
        [0.7345, 0.8845, 0.9286]])