In [1]:
import torch 


Manipulating Tensors (Tensor Operations)

In [2]:
tensor1 = torch.tensor([1,2,3])
tensor1 + 10 #addition 

tensor([11, 12, 13])

In [3]:
tensor1 * 10 #multiply 

tensor([10, 20, 30])

In [4]:
tensor2 = torch.rand(3,4)
print(tensor2)

tensor([[0.6576, 0.0295, 0.5363, 0.8680],
        [0.3457, 0.3904, 0.1097, 0.5756],
        [0.5663, 0.0921, 0.0493, 0.3398]])


ELEMENT WISE MULTIPLICATION && MATRIX WISE MULITPLICATION

In [7]:
tensortemp = torch.mul(tensor2,10) #This is ELEMENT WISE MATRIX MULTIPLICATION : we multiply by a scalar value 
print(tensortemp)


tensor([[6.5763, 0.2954, 5.3629, 8.6796],
        [3.4567, 3.9039, 1.0970, 5.7561],
        [5.6628, 0.9214, 0.4932, 3.3979]])


In [10]:
tensor3 = torch.rand(4,3)
print(tensor3)

tensor([[0.5792, 0.7044, 0.1783],
        [0.8040, 0.6583, 0.2238],
        [0.9208, 0.1078, 0.7936],
        [0.1610, 0.5411, 0.1669]])


In [11]:
tensortemp * tensor2 #THIS IS AN ELEMENT WISE MULTIPLICATION. each element got multiplied with the corresponding matrix's same element according to the position. 

tensor([[4.3247, 0.0087, 2.8760, 7.5336],
        [1.1949, 1.5240, 0.1204, 3.3132],
        [3.2067, 0.0849, 0.0243, 1.1546]])

In [12]:
tensor2 * tensor3 #this is an error even though this is 3 by 4 * 4 by 3. because its ELEMENT MULT 

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [17]:
torch.matmul(tensor2,tensor3) #THIS IS MATRIX MULTIPLICATION WHICH HAPPENS IN NEURAL NETWORKS 

tensor([[0.8571, 0.7582, 0.6610],
        [1.1531, 1.5724, 1.7039],
        [0.7345, 0.8845, 0.9286]])