In [1]:

import torch

Reshaping, Stacking, Squeezing & Unsqueezing Tensors

Reshaping: changing the shape of a tensor 

VIEW: Return a view of a tensor in a certain shape but have the memory as the original tensor 

Stacking : combine multiple tensors on top of each other  

Squeeze : removes all '1' dimensions from a tensor 

Unsqueeze : adds a dimension to a target tensor 
Permute : Return a view of the input with dimensions permuted (swapped) in a certain way 

In [13]:
#lets create a tensor 
import torch 
x = torch.arange(1.,11.,)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [14]:
#Add an extra dimension 

reshaped_x = x.reshape(5,2)  #be careful, you have to fit the numbers in a shape that can hold that many numbers. 
reshaped_x, reshaped_x.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [16]:
#Change the view: But remember when we change the value of Z elements, it impacts x too. Its basically a pointer to x but with the shape that we defined for z using view()
z = x.view(10,1)
z, z.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

Z has the memory of x. Changing Z changes x. 


In [17]:
z[:,0] =100 #all row's first element. 
z

tensor([[100.],
        [100.],
        [100.],
        [100.],
        [100.],
        [100.],
        [100.],
        [100.],
        [100.],
        [100.]])

In [19]:
x #see how x changed since z was changed. 

tensor([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

Stacking

In [20]:
#Stacking 
a = torch.tensor([[2,4,6],
                  [4,8,12]])
a, a.shape

(tensor([[ 2,  4,  6],
         [ 4,  8, 12]]),
 torch.Size([2, 3]))

In [21]:
a_stacked = torch.stack([a,a,a],dim=0)
a_stacked, a_stacked.shape

(tensor([[[ 2,  4,  6],
          [ 4,  8, 12]],
 
         [[ 2,  4,  6],
          [ 4,  8, 12]],
 
         [[ 2,  4,  6],
          [ 4,  8, 12]]]),
 torch.Size([3, 2, 3]))

In [24]:
a_stacked1 = torch.stack([a,a,a],dim=1)
a_stacked1, a_stacked1.shape

(tensor([[[ 2,  4,  6],
          [ 2,  4,  6],
          [ 2,  4,  6]],
 
         [[ 4,  8, 12],
          [ 4,  8, 12],
          [ 4,  8, 12]]]),
 torch.Size([2, 3, 3]))

In [10]:
a_stacked2 = torch.stack([a,a,a],dim=2)
a_stacked2, a_stacked2.shape

(tensor([[[ 2,  2,  2],
          [ 4,  4,  4],
          [ 6,  6,  6]],
 
         [[ 4,  4,  4],
          [ 8,  8,  8],
          [12, 12, 12]]]),
 torch.Size([2, 3, 3]))

In [25]:
a_stacked3 = torch.stack([a,a,a],dim=-1)
a_stacked3, a_stacked3.shape

(tensor([[[ 2,  2,  2],
          [ 4,  4,  4],
          [ 6,  6,  6]],
 
         [[ 4,  4,  4],
          [ 8,  8,  8],
          [12, 12, 12]]]),
 torch.Size([2, 3, 3]))