In [3]:

import torch

Reshaping, Stacking, Squeezing & Unsqueezing Tensors

Reshaping: changing the shape of a tensor 

VIEW: Return a view of a tensor in a certain shape but have the memory as the original tensor 

Stacking : combine multiple tensors on top of each other  

Squeeze : removes all '1' dimensions from a tensor 

Unsqueeze : adds a dimension to a target tensor 
Permute : Return a view of the input with dimensions permuted (swapped) in a certain way 

In [1]:
#lets create a tensor 
import torch 
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [2]:
#Add an extra dimension 

x_reshaped = x.reshape(9,1) #be careful, you have to fit the numbers in a shape that can hold that many numbers. 
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [5]:
#Change the view : 

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Z has the memory of x. Changing Z changes x. 


In [6]:
z[:,0] =1 #all row's first element. 
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

Stacking

In [7]:
#Stacking 
a = torch.tensor([[2,4,6],
                  [4,8,12]])
a, a.shape

(tensor([[ 2,  4,  6],
         [ 4,  8, 12]]),
 torch.Size([2, 3]))

In [8]:
a_stacked = torch.stack([a,a,a],dim=0)
a_stacked, a_stacked.shape

(tensor([[[ 2,  4,  6],
          [ 4,  8, 12]],
 
         [[ 2,  4,  6],
          [ 4,  8, 12]],
 
         [[ 2,  4,  6],
          [ 4,  8, 12]]]),
 torch.Size([3, 2, 3]))

In [9]:
a_stacked1 = torch.stack([a,a,a],dim=1)
a_stacked1, a_stacked1.shape

(tensor([[[ 2,  4,  6],
          [ 2,  4,  6],
          [ 2,  4,  6]],
 
         [[ 4,  8, 12],
          [ 4,  8, 12],
          [ 4,  8, 12]]]),
 torch.Size([2, 3, 3]))

In [10]:
a_stacked2 = torch.stack([a,a,a],dim=2)
a_stacked2, a_stacked2.shape

(tensor([[[ 2,  2,  2],
          [ 4,  4,  4],
          [ 6,  6,  6]],
 
         [[ 4,  4,  4],
          [ 8,  8,  8],
          [12, 12, 12]]]),
 torch.Size([2, 3, 3]))

In [11]:
a_stacked3 = torch.stack([a,a,a],dim=-1)
a_stacked3, a_stacked3.shape

(tensor([[[ 2,  2,  2],
          [ 4,  4,  4],
          [ 6,  6,  6]],
 
         [[ 4,  4,  4],
          [ 8,  8,  8],
          [12, 12, 12]]]),
 torch.Size([2, 3, 3]))