In [1]:
import torch 

In [4]:
#Squeeze: 

x = torch.zeros(2,1,2,1,2)
x, x.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [7]:
#all 1 dimensions are gone :

y = torch.squeeze(x)
y, y.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [9]:
z = torch.squeeze(x,0)
z, z.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [13]:
#Permute for Images 

x_original = torch.rand(size=(224,224,3)) #height, width, channels 
x_original.shape


torch.Size([224, 224, 3])

In [12]:
#we will convert it to channels, height, width 
x_permuted = x_original.permute(2,0,1) #channles, height, width 
x_permuted.shape


torch.Size([3, 224, 224])