In [1]:
import torch 


In [4]:
x = torch.arange(1.,9.).reshape(2,2,2)
x

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [7]:
#index the outer most dimension 
x[0], x[1]

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[5., 6.],
         [7., 8.]]))

In [11]:
x[0][1], x[0,1] #THESE TWO MEAN THE SAME THING, REMEMBER THIS 

(tensor([3., 4.]), tensor([3., 4.]))

In [12]:
x[1,1,0] 

tensor(7.)

In [13]:
x[:,1]

tensor([[3., 4.],
        [7., 8.]])